export const Types = {
    LOAD_MOVIES_REQUEST: 'movies/LOAD_MOVIES_REQUEST',
    LOAD_MOVIES_SUCCESS: 'movies/LOAD_MOVIES_SUCCESS',

    LOAD_DETAILS_REQUEST: 'details/LOAD_DETAILS_REQUEST',
    LOAD_DETAILS_SUCCESS: 'details/LOAD_DETAILS_SUCCESS',

    SHOW_DETAILS: 'navigation/SHOW_DETAILS',

    SEARCH_REQUEST: 'search/SEARCH_REQUEST',
    SEARCH_SUCCESS: 'search/SEARCH_SUCCESS',

    ERROR: 'ERROR',
};

